sudo: false
language: ruby

rvm:
  - 2.5
  - 2.4
  - ruby-head

before_install: 
  - gem install bundler -v 1.16.2
  - npm install -g puppeteer
  - npm install

matrix:
  allow_failures:
    - rvm: ruby-head
